apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cicd-app
  labels:
    app: my-cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cicd-app
  template:
    metadata:
      labels:
        app: my-cicd-app
    spec:
      containers:
        - name: my-cicd-container
          image: docker.io/eset0074/my-cicd-app:1
          ports:
            - containerPort: 5000
